### ISSUE TITLE
Goed onderweg

### ISSUE THREAD

**Issue by Theo-denBlanken** [bobvberckel/FRO-JSON-Schoolopdracht#1]
maar nu eerst wel 2 eigen boeken toevoegen aan het JSON-bestand en een meta-tag author toevoegen

**Comment by bobvberckel** [comment]
Gedaan, er zijn nu 5 boeken toegevoegd aan het JSON Bestand.

Ik wilde dit in JSON duidelijk maken door middel van een comment, maar blijkbaar is dit niet toegestaan in JSON.

Het lijstje van de boeken (Staat ook in de commit!):

- Barack Obama - A Promised Land (ENG)
- Barack Obama - Een Beloofd Land (NL)
- Michelle Obama - Becoming (ENG)
- Michelle Obama - Mijn Verhaal (NL)
- Michail Gorbatsjov - Perestrojka (NL)

De META Tag Author is nu ook toegevoegd aan de head.

Zal vandaag gepushed worden nadat Issue #2 en #3 ook zijn verwerkt.
